tcp broker
patio-python/patio pull request #1
Opened 2023-05-29 09:08 UTC by mosquito

2023-05-31 17:37 UTC, Alviner commented on examples/memory/multiplication-decorator.py
> +    async with MemoryBroker(max_workers=4) as broker:
abstract worker expected executor but get max_worker argument

2023-05-31 17:37 UTC, Alviner commented on patio/executor/base.py
> +    max_workers: int = 4
let's make classvar names uppercase?

2023-06-06 22:26 UTC, tzoiker requested changes

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +large distributed projects, the general idea is the user simply split the
large distributed projects. The general idea is that the user simply splits the

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +project code base to tasks and where those who call and perform them.
> and where those who call and perform them.

I didn't understand that

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +Also, this should help to your project scale horizontally. By make available
Also, this should help your project to scale horizontally. It allows to make workers or callers available across the network using embedded TCP, or using plugins to communicate through the existing messaging infrastructure.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +For more information about what the essences are responsible for, see below.
> what the essences are responsible for

Didn't understand that

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +The main idea in creating this library was to create a maximally
The main idea in developing this library was to create a

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `Broker` - The actor who distributes tasks in your distributed
An actor delegating tasks in your distributed

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `Executor` - The thing which execute functions from the registry
A(?) thing which executes functions from the registry

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +This is a container of functions for their subsequent execution.
This is a container of functions available for execution.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +You can register a function by specific name or without it,
You can register a function with or without an explicit name.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +in which case the function is assigned a unique name that depends on
In the latter case the function is assigned a unique name

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +This registry does not necessarily have to match on the calling and called
The registries do not necessarily have to match on the calling and the called (executed) sides. However, for the functions that are registered without a name they must, and, then, you don't need to pass a function's name, but the function itself when it is called.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +An optional ``project`` parameter, this is essentially like a namespace
There is an optional ``project`` parameter, which acts as a namespace helping to avoid functions with the same name to clash in different projects .

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +name. It is recommended to specify it and the broker should also use this
It is recommended to specify it, in which case it must be passed both to the registry and to the broker.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +# Will be registered with auto generated name
with an auto generated name

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +You can either manually register elements or use a
You can either manually register functions or use a

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +An Executor is an entity that executes local functions from registry.
a registry.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `AsyncExecutor` - Implements pool of asynchronous tasks
Pool of asynchronous tasks

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `ThreadPoolExecutor` - Implements pool of threads
Pool of threads

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `ProcessPoolExecutor` - Implements pool of processes
Pool of processes

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +* `NullExecutor` - Implements nothing and exists just for forbid execute
Dummy executor existing only to explicitly forbid executing something

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +Its role is to reliably execute jobs without taking too much so as not to
Whose role?

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +The executor instance is passing to the broker, it's usually applies
Didn't understand this paragraph

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +for the distribution to the user implementation. In this way, task
This way, task

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +or something else.
or anything else.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +This package is implemented by the following brokers:
This package implements the following brokers:

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +It's useful if you don't need to assign tasks now, but it's a good help
It's a good start if you don't need to assign tasks in a distributed fashion now.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +In fact, it's a simple way to run tasks in the executor from other
In fact, it's a simple way to run tasks in the executor from the other

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +This allows you to make your tasks distributed without resorting to
It allows you to make your tasks distributed without resorting to external message brokers.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +them, and it is also possible in mixed mode.
in a mixed mode.

2023-06-06 22:26 UTC, tzoiker commented on README.md
> +  -newkey rsa:2048 \
Me no likey 🐵 elliptic curve?

2023-06-07 08:30 UTC, mosquito commented on README.md
> +  -newkey rsa:2048 \
Just for maximal compatibility.

2023-06-08 09:47 UTC, tzoiker commented on README.md
> +triggers this background tasks.
```suggestion
the projects code base into functions of two roles – background tasks and triggers of these background tasks.
```

2023-06-08 10:47 UTC, merged